name: Build
on:
    push:
        tags:
            - '*'

jobs:
    build:
        name: Build
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 20
            - name: Install g++-multilib
              if: matrix.os == 'ubuntu-latest'
              run: sudo apt-get install g++-multilib
            - name: Install dependencies
              run: npm install
            - name: Transpile
              run: npm run build
            - name: Publish
              run: npm run publish
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}